### ISSUE TITLE
Crash at the beginning of the game

### ISSUE THREAD

**Issue by BaiFeng666** [Sardelka9515/scripthookvdotnetcore#6]
---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Assertion failed!

Program: ...ommon\Grand Theft Auto V\ScriptHookVDotNetCore.asi
File: D:\Github\scripthookvdotnetcore\src\core\nativehost.cpp
Line: 48

Expression: load_assembly_and_get_function_pointer != nullptr && "Failure: get_dotnet_load_assembly()"

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts

(Press Retry to debug the application - JIT must be enabled)

**Comment by Sardelka9515** [comment]
Make sure you have .NET 7 desktop runtime properly installed

**Comment by BaiFeng666** [comment]
> Make sure you have .NET 7 desktop runtime properly installed

I installed it, but  still reporting errors...

**Comment by BaiFeng666** [comment]
---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Assertion failed!

Program: ...ommon\Grand Theft Auto V\ScriptHookVDotNetCore.asi
File: D:\Github\scripthookvdotnetcore\src\core\nativehost.cpp
Line: 48

Expression: load_assembly_and_get_function_pointer != nullptr && "Failure: get_dotnet_load_assembly()"

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts

(Press Retry to debug the application - JIT must be enabled)

**Comment by Hydraxonn** [comment]
This issue only comes up when .NET 7 is not installed properly. Please ensure you've downloaded the proper .NET 7 runtime for your machine.

**Comment by Hydraxonn** [comment]
![Screenshot_20230330_114330_Samsung Internet](https://user-images.githubusercontent.com/46947651/228891644-5fdc0c33-9c6e-4c9e-a50f-59e8b96c80af.jpg)

**Comment by BaiFeng666** [comment]
> This issue only comes up when .NET 7 is not installed properly. Please ensure you've downloaded the proper .NET 7 runtime for your machine.

![Pic](https://user-images.githubusercontent.com/69395668/229014934-3ec61925-2c4f-4ae2-af23-727f0ade62de.png)

I think I installed them all

**Comment by Sardelka9515** [comment]
Can you show the screenshot of your game directory? You need to put all files in it, not just the asi

**Comment by BaiFeng666** [comment]
> Can you show the screenshot of your game directory? You need to put all files in it, not just the asi
![image](https://user-images.githubusercontent.com/69395668/229015899-29830241-0370-4e18-84fe-9111e7323b71.png)

/(ㄒoㄒ)/~~

**Comment by Sardelka9515** [comment]
Looks like it started properly?

**Comment by BaiFeng666** [comment]
> Looks like it started properly?

No It will report an error
It's like what I posted in the beginning

**Comment by Sardelka9515** [comment]
Did you have ScriptHookVDotNetCore.runtimeconfig.json?

**Comment by BaiFeng666** [comment]
> Did you have ScriptHookVDotNetCore.runtimeconfig.json?

yes,  in the build file, I didn't put it in the game directory

**Comment by Sardelka9515** [comment]
I said all files, you need to put it in the game directory as well

**Comment by Sardelka9515** [comment]
It's included in the release, so...

**Comment by BaiFeng666** [comment]
> It's included in the release, so...
I forgot the most basic knowledge
Now it's working, thank you 我是傻逼
