### ISSUE TITLE
ScriptHookVDotNetCore prevents ReShade (dxgi.dll) from loading

### ISSUE THREAD

**Issue by Hydraxonn** [Sardelka9515/scripthookvdotnetcore#7]
If I remove ScriptHookVDotNetCore.asi, ReShade works no problem without any issues. Strangely, in the SHVDNC settings INI, when I enable the debug console window, then ReShade works with SHVDNC no problem. Hopefully this won't be too hard to fix, but I'm not sure why these two are interacting with each other in the first place. Thanks!

**Comment by Sardelka9515** [comment]
AFAIK dxgi.dll is part of directx, might be utilized by reshade to perform API hijacking. No idea why is causing problem, did you see any error message?

When the debug console is enabled, CLR initialization is delayed by 10 seconds to prevent the game from closing the window, which may allow reshade to perform proper initialization?

**Comment by Hydraxonn** [comment]
No error message, ReShade just doesn't load. That ten second delay may be it, what if the non-debug option also had that delay? I'd be happy to test a version of that

**Comment by Sardelka9515** [comment]
Can you try this build?
[ScriptHookVDotNetCore.zip](https://github.com/Sardelka9515/scripthookvdotnetcore/files/11131072/ScriptHookVDotNetCore.zip)

**Comment by Hydraxonn** [comment]
Yup, that fixes it. Brilliant work, as always!
